MVNW_VERBOSE=true MAVEN_CONFIG="-gs /etc/maven/settings.xml" MVNW_REPOURL=https://maven.ghg.transtrend.com/public JAVA_HOME=/usr/lib/jvm/zulu21 https_proxy=http://proxy:3128  ./mvnw install:install-file -Dfile=/home/ljp/ilink3/artio-ilink3/artio-core/build/libs/artio-core-0.154-SNAPSHOT.jar    -DgroupId=uk.co.real-logic    -DartifactId=artio-core    -Dversion=0.154-SNAPSHOT    -Dpackaging=jar    -DgeneratePom=true
MVNW_VERBOSE=true MAVEN_CONFIG="-gs /etc/maven/settings.xml" MVNW_REPOURL=https://maven.ghg.transtrend.com/public JAVA_HOME=/usr/lib/jvm/zulu21 https_proxy=http://proxy:3128  ./mvnw install:install-file -Dfile=/home/ljp/ilink3/artio-ilink3/artio-codecs/build/libs/artio-codecs-0.154-SNAPSHOT.jar    -DgroupId=uk.co.real-logic    -DartifactId=artio-codecs    -Dversion=0.154-SNAPSHOT    -Dpackaging=jar    -DgeneratePom=true
MVNW_VERBOSE=true MAVEN_CONFIG="-gs /etc/maven/settings.xml" MVNW_REPOURL=https://maven.ghg.transtrend.com/public JAVA_HOME=/usr/lib/jvm/zulu21 https_proxy=http://proxy:3128  ./mvnw install:install-file -Dfile=/home/ljp/ilink3/artio-ilink3/artio-ilink3-impl/build/libs/artio-ilink3-impl-0.154-SNAPSHOT.jar    -DgroupId=uk.co.real-logic    -DartifactId=artio-ilink3-impl    -Dversion=0.154-SNAPSHOT    -Dpackaging=jar    -DgeneratePom=true
MVNW_VERBOSE=true MAVEN_CONFIG="-gs /etc/maven/settings.xml" MVNW_REPOURL=https://maven.ghg.transtrend.com/public JAVA_HOME=/usr/lib/jvm/zulu21 https_proxy=http://proxy:3128  ./mvnw install:install-file -Dfile=/home/ljp/ilink3/artio-ilink3/artio-ilink3-codecs/build/libs/artio-ilink3-codecs-0.154-SNAPSHOT.jar    -DgroupId=uk.co.real-logic    -DartifactId=artio-ilink3-codecs    -Dversion=0.154-SNAPSHOT    -Dpackaging=jar    -DgeneratePom=true

MVNW_VERBOSE=true MAVEN_CONFIG="-gs /etc/maven/settings.xml" MVNW_REPOURL=https://maven.ghg.transtrend.com/public JAVA_HOME=/usr/lib/jvm/zulu21 https_proxy=http://proxy:3128  ./mvnw install:install-file -Dfile=/home/ljp/ilink3/artio-ilink3/artio-core/build/libs/artio-core-0.154-SNAPSHOT-sources.jar    -DgroupId=uk.co.real-logic    -DartifactId=artio-core    -Dversion=0.154-SNAPSHOT    -Dpackaging=jar    -DgeneratePom=true -Dclassifier=sources
MVNW_VERBOSE=true MAVEN_CONFIG="-gs /etc/maven/settings.xml" MVNW_REPOURL=https://maven.ghg.transtrend.com/public JAVA_HOME=/usr/lib/jvm/zulu21 https_proxy=http://proxy:3128  ./mvnw install:install-file -Dfile=/home/ljp/ilink3/artio-ilink3/artio-codecs/build/libs/artio-codecs-0.154-SNAPSHOT-sources.jar    -DgroupId=uk.co.real-logic    -DartifactId=artio-codecs    -Dversion=0.154-SNAPSHOT    -Dpackaging=jar    -DgeneratePom=true -Dclassifier=sources
MVNW_VERBOSE=true MAVEN_CONFIG="-gs /etc/maven/settings.xml" MVNW_REPOURL=https://maven.ghg.transtrend.com/public JAVA_HOME=/usr/lib/jvm/zulu21 https_proxy=http://proxy:3128  ./mvnw install:install-file -Dfile=/home/ljp/ilink3/artio-ilink3/artio-ilink3-impl/build/libs/artio-ilink3-impl-0.154-SNAPSHOT-sources.jar -DgroupId=uk.co.real-logic    -DartifactId=artio-ilink3-impl    -Dversion=0.154-SNAPSHOT    -Dpackaging=jar    -DgeneratePom=true -Dclassifier=sources
MVNW_VERBOSE=true MAVEN_CONFIG="-gs /etc/maven/settings.xml" MVNW_REPOURL=https://maven.ghg.transtrend.com/public JAVA_HOME=/usr/lib/jvm/zulu21 https_proxy=http://proxy:3128  ./mvnw install:install-file -Dfile=/home/ljp/ilink3/artio-ilink3/artio-ilink3-codecs/build/libs/artio-ilink3-codecs-0.154-SNAPSHOT-sources.jar    -DgroupId=uk.co.real-logic    -DartifactId=artio-ilink3-codecs    -Dversion=0.154-SNAPSHOT    -Dpackaging=jar    -DgeneratePom=true -Dclassifier=sources

MVNW_VERBOSE=true MAVEN_CONFIG="-gs /etc/maven/settings.xml" MVNW_REPOURL=https://maven.ghg.transtrend.com/public JAVA_HOME=/usr/lib/jvm/zulu21 https_proxy=http://proxy:3128  ./mvnw clean package

cp /home/ljp/ilink3/quickfixj-ilink3/target/quickfixj-ilink3-1.0.0-SNAPSHOT-jar-with-dependencies.jar  /home/ljp/IdeaProjects/FixEngine/libs/quickfixj-ilink3-1.0.0-SNAPSHOT-jar-with-dependencies.jar

